const chatbotdata = {
  name: "Rahul Sharma",
  email: "rahul1sharma1919@gmail.com",
  phone: "+91-9554888377",
  location: "Kanpur, UP, India",
  education: ["B.Tech in Computer Science Engineering, 2024"],
  experience: [
    "Technical Analyst Intern at GeeksforGeeks (Nov 2023 – Aug 2024)",
  ],
  skills: [
    "React.js",
    "Tailwind CSS",
    "Express.js",
    "Python",
    "C++",
    "HTML",
    "CSS",
    "GSAP",
    "REST API",
    "SQL",
    "MySQL",
    "Firebase",
    "Git",
    "GitHub",
    "DSA",
    "Front End Development",
  ],
  projects: [
    "Resume.AI - AI Resume Analyzer – React + React Router 7 + Puter AI + Tailwind CSS",
    "Zephyrus Gaming Website – React + GSAP + Tailwind CSS",
    "Web Scraping System – Python + Selenium Webdriver + HTML + CSS",
    "Personal Portfolio Website – React + Bootstrap + Framer Motion",
    "DCS Landing Page – Freelance project - HTML + CSS + Bootstrap + Git",
  ],
  hobbies: [
    "Playing video games",
    "Reading Adventurous & mysterious books",
    "Traveling",
    "Listening to music",
    "Watching Animes",
    "Watching Sci-Fi, Horror, Thriller, Mysterious & Comedy movies",
  ],
  jokes: [
    "I was coded to be funny, but trust me, my jokes compile better than yours 😂",
    "Why did the programmer quit his job? Because he didn’t get arrays! 😎",
    "I’m Zeppy, Rahul’s assistant. Think of me as Clippy, but cooler 🎮",
    "Knock knock… oh wait, I forgot the punchline 🤖😂",
    "Why did the React developer go broke? Because he kept working for free hooks! 😂",
    "I would tell you a JavaScript joke, but you wouldn't get it (undefined). 😅",
    "Why did the programmer quit his job? Because he didn't get arrays! 🤣",
  ],
};

export default chatbotdata;
