// index.js
export const experiences = [
  {
    title: "Technical Analyst Intern",
    employer: "GeeksforGeeks",
    date: "Nov 2023 – Aug 2024",
    contents: [
      "Reviewed 500+ coding solutions in DSA & algorithms, identifying and fixing 100+ critical errors to improve efficiency.",
      "Worked closely with mentors and senior engineers, gaining hands-on experience in writing clean and efficient code.",
      "Assisted in structuring 50+ technical articles and applied SEO strategies (keywords, meta-tags, formatting), increasing content reach by 25%.",
      "Enhanced 200+ problem statements for clarity and rewrote editorials with step-by-step explanations, improving learner engagement by 30%.",
    ],
  },
  {
    title: "Freelance Developer",
    employer: "Self-Employed",
    date: "2024 – Present",
    contents: [
      "Delivered freelance projects including a landing page for DCS and multiple responsive websites using React.js, Tailwind CSS, and modern web tools.",
      "Developed and deployed a personal portfolio website to showcase projects, skills, and professional experience.",
      "Collaborated with international clients to design solutions tailored for business needs in the US and Canada.",
      "Continuously enhancing technical skills and expanding expertise in modern web development and back-end technologies.",
    ],
  },
  {
    title: "AI Trainer - Freelancer",
    employer: "Outlier.ai",
    date: "2024 – Present",
    contents: [
      "Trained AI models by designing, refining, and testing prompts to evaluate performance across different tasks.",
      "Compared responses generated by Model A and Model B, grading them based on accuracy, clarity, and alignment with human expectations.",
      "Provided detailed feedback to improve reasoning ability, correctness in coding-related queries, and natural language generation quality.",
      "Specialized in software engineering and coding tasks, ensuring AI systems deliver precise, optimized, and production-ready solutions.",
    ],
  },
];

export const projects = [
  {
    id: 1,
    name: "Resume.AI - AI Resume Analyzer",
    description:
      "AI-powered resume analyzer that provides ATS scores, detailed feedback, and keyword suggestions for job applications.",
    href: "https://ai-resume-analyzer-psi-ivory.vercel.app/",
    image: "/assets/projects/ai-resume-analyzer.jpg",
    bgImage: "/assets/backgrounds/blanket.jpg",
    frameworks: [
      { id: 1, name: "React" },
      { id: 2, name: "React Router 7" },
      { id: 3, name: "Puter.js" },
      { id: 4, name: "Tailwind CSS" },
    ],
  },
  {
    id: 2,
    name: "Zephyrus Gaming Website",
    description:
      "A dynamic gaming website featuring smooth animations, interactive components, and a responsive design for engaging user experience.",
    href: "https://zephyrus-gaming.vercel.app/",
    image: "/assets/projects/zephyrus-gaming.jpg",
    bgImage: "/assets/backgrounds/curtains.jpg",
    frameworks: [
      { id: 1, name: "React.js" },
      { id: 2, name: "Vercel" },
      { id: 3, name: "GSAP" },
      { id: 4, name: "Tailwind CSS" },
    ],
  },
  {
    id: 3,
    name: "Web Scraping with Python",
    description:
      "A web scraping system that extracts and processes large datasets from multiple websites, with real-time visualization for analysis.",
    href: "",
    image: "/assets/projects/webscraping-with-python.png",
    bgImage: "/assets/backgrounds/map.jpg",
    frameworks: [
      { id: 1, name: "Python" },
      { id: 2, name: "Selenium WebDriver" },
      { id: 3, name: "HTML" },
      { id: 4, name: "CSS" },
    ],
  },
  {
    id: 4,
    name: "DCS - Landing Page",
    description:
      "A freelance project creating a simple landing page for Dodong Consultancy Services (DCS), highlighting web and app solutions for businesses in the US and Canada.",
    href: "https://rahulsharma1919.github.io/Freelance-project//",
    image: "/assets/projects/dcs-landing-page.jpg",
    bgImage: "/assets/backgrounds/poster.jpg",
    frameworks: [
      { id: 1, name: "HTML" },
      { id: 2, name: "CSS" },
      { id: 3, name: "Bootstrap" },
      { id: 4, name: "Git" },
    ],
  },
  {
    id: 5,
    name: "Personal Portfolio Website",
    description:
      "A personal portfolio website showcasing projects, skills, and contact information with an attractive, responsive design.",
    href: "https://reactfolio-rahul-sharma.vercel.app/",
    image: "/assets/projects/portfolio.jpg",
    bgImage: "/assets/backgrounds/table.jpg",
    frameworks: [
      { id: 1, name: "React.js" },
      { id: 2, name: "Tailwind CSS" },
      { id: 3, name: "Motion" },
      { id: 4, name: "Vite.js" },
    ],
  },
  {
    id: 6,
    name: "3D Dev Portfolio",
    description:
      "A gaming platform featuring discounted titles, top sellers, and genre-based browsing.",
    href: "https://3d-dev-personal-portfolio.vercel.app/",
    image: "/assets/projects/3d-dev-portfolio.jpg",
    bgImage: "/assets/backgrounds/curtains.jpg",
    frameworks: [
      { id: 1, name: "React.js" },
      { id: 2, name: "React 3 Fiber" },
      { id: 3, name: "GSAP" },
      { id: 4, name: "Email.js" },
      { id: 5, name: "Aceternity UI" },
      { id: 6, name: "Tailwind CSS" },
    ],
  },
];
export const socials = [
  { name: "LinkedIn", href: "https://linkedin.com/in/rahulsharma1919" },
  { name: "GitHub", href: "https://github.com/rahulsharma1919" },
  { name: "Leetcode", href: "https://www.leetcode.com/rahul1sharma1919" },
  { name: "Instagram", href: "https://instagram.com/_rahul_sharma.9554" },
  { name: "Twitter", href: "https://twitter.com/rahulsh01554528" },
];
